In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/leak-detection/Dataset for Leak Detection and Localization in Water Distribution Systems/Dataset for Leak Detection and Localization in Water Distribution Systems/Hydrophone/Branched/Gasket Leak/BR_GL_Transient_NS_H1.raw
/kaggle/input/leak-detection/Dataset for Leak Detection and Localization in Water Distribution Systems/Dataset for Leak Detection and Localization in Water Distribution Systems/Hydrophone/Branched/Gasket Leak/BR_GL_0.47 LPS_H2.raw
/kaggle/input/leak-detection/Dataset for Leak Detection and Localization in Water Distribution Systems/Dataset for Leak Detection and Localization in Water Distribution Systems/Hydrophone/Branched/Gasket Leak/BR_GL_0.18 LPS_H1.raw
/kaggle/input/leak-detection/Dataset for Leak Detection and Localization in Water Distribution Systems/Dataset for Leak Detection and Localization in Water Distribution Systems/Hydrophone/Branched/Gasket Leak/BR_GL_0.47 LPS_H1.raw
/kaggle/input/leak-detection/Dataset for Leak Detection and Localization

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sklearn
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, SimpleRNN, GRU
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from pandas_profiling import ProfileReport

# import warnings
# warnings.filterwarnings('ignore')

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: l

In [3]:
data_dir = "/kaggle/input/leak-detection/Dataset for Leak Detection and Localization in Water Distribution Systems/Dataset for Leak Detection and Localization in Water Distribution Systems/Hydrophone/Branched/Circumferential Crack/"
file_extension = ".raw"
sampling_rate = 8000

all_data = []

# Loop through all .raw files in the directory
for filename in os.listdir(data_dir):
    if filename.endswith(file_extension):
        file_path = os.path.join(data_dir, filename)
        
        with open(file_path, "rb") as file:
            file_content = file.read()
            
        # Convert binary data to NumPy array that will be a dataframe
        hydrophone_data =  pd.DataFrame(np.frombuffer(file_content, dtype=np.int16))
        
        all_data.append(hydrophone_data)
        
# Concatenate all DataFrames into a single DataFrame
df = pd.concat(all_data, axis=1, ignore_index=True)

df["LeakType"] = "Circumferential Crack"

In [4]:
data_dir = "/kaggle/input/leak-detection/Dataset for Leak Detection and Localization in Water Distribution Systems/Dataset for Leak Detection and Localization in Water Distribution Systems/Hydrophone/Branched/Gasket Leak/"
file_extension = ".raw"
sampling_rate = 8000

all_data = []

# Loop through all .raw files in the directory
for filename in os.listdir(data_dir):
    if filename.endswith(file_extension):
        file_path = os.path.join(data_dir, filename)
        
        with open(file_path, "rb") as file:
            file_content = file.read()
            
        # Convert binary data to NumPy array that will be a dataframe
        hydrophone_data =  pd.DataFrame(np.frombuffer(file_content, dtype=np.int16))
        
        all_data.append(hydrophone_data)
        
# Concatenate all DataFrames into a single DataFrame
df1 = pd.concat(all_data, axis=1, ignore_index=True)

df1["LeakType"] = "Gasket Leak"

In [5]:
data_dir = "/kaggle/input/leak-detection/Dataset for Leak Detection and Localization in Water Distribution Systems/Dataset for Leak Detection and Localization in Water Distribution Systems/Hydrophone/Branched/Longitudinal Crack/"
file_extension = ".raw"
sampling_rate = 8000

all_data = []

# Loop through all .raw files in the directory
for filename in os.listdir(data_dir):
    if filename.endswith(file_extension):
        file_path = os.path.join(data_dir, filename)
        
        with open(file_path, "rb") as file:
            file_content = file.read()
            
        # Convert binary data to NumPy array that will be a dataframe
        hydrophone_data =  pd.DataFrame(np.frombuffer(file_content, dtype=np.int16))
        
        all_data.append(hydrophone_data)
        
# Concatenate all DataFrames into a single DataFrame
df2 = pd.concat(all_data, axis=1, ignore_index=True)

df2["LeakType"] = "Longitudinal Crack"

In [6]:
data_dir = "/kaggle/input/leak-detection/Dataset for Leak Detection and Localization in Water Distribution Systems/Dataset for Leak Detection and Localization in Water Distribution Systems/Hydrophone/Branched/NonLeak/"
file_extension = ".raw"
sampling_rate = 8000

all_data = []

# Loop through all .raw files in the directory
for filename in os.listdir(data_dir):
    if filename.endswith(file_extension):
        file_path = os.path.join(data_dir, filename)
        
        with open(file_path, "rb") as file:
            file_content = file.read()
            
        # Convert binary data to NumPy array that will be a dataframe
        hydrophone_data =  pd.DataFrame(np.frombuffer(file_content, dtype=np.int16))
        
        all_data.append(hydrophone_data)
        
# Concatenate all DataFrames into a single DataFrame
df3 = pd.concat(all_data, axis=1, ignore_index=True)

df3["LeakType"] = "NonLeak"

In [7]:
data_dir = "/kaggle/input/leak-detection/Dataset for Leak Detection and Localization in Water Distribution Systems/Dataset for Leak Detection and Localization in Water Distribution Systems/Hydrophone/Branched/Orifice Leak/"
file_extension = ".raw"
sampling_rate = 8000

all_data = []

# Loop through all .raw files in the directory
for filename in os.listdir(data_dir):
    if filename.endswith(file_extension):
        file_path = os.path.join(data_dir, filename)
        
        with open(file_path, "rb") as file:
            file_content = file.read()
            
        # Convert binary data to NumPy array that will be a dataframe
        hydrophone_data =  pd.DataFrame(np.frombuffer(file_content, dtype=np.int16))
        
        all_data.append(hydrophone_data)
        
# Concatenate all DataFrames into a single DataFrame
df4 = pd.concat(all_data, axis=1, ignore_index=True)

df4["LeakType"] = "Orifice Leak"

In [8]:
data = pd.concat([df, df1, df2, df3, df4], axis=0)
data = data.sample(frac = 1)
data

0       1        2       3       4       5        6       7  \
303190      0.0     0.0      0.0     0.0     0.0     0.0      0.0     0.0   
34830       0.0     0.0      0.0     0.0     0.0     0.0      0.0     0.0   
745073      NaN     NaN      NaN     NaN     NaN     NaN      NaN  1830.0   
91507   10450.0  8784.0  17393.0  6505.0 -4753.0  1974.0 -11596.0 -5918.0   
599857   3318.0     NaN   2686.0     NaN  9796.0   106.0  -1705.0   373.0   
...         ...     ...      ...     ...     ...     ...      ...     ...   
332203   3731.0 -1089.0  10581.0  8808.0  4565.0  2347.0   4008.0  6096.0   
643244      NaN     0.0      NaN     NaN     NaN     NaN      NaN     0.0   
81416       0.0     0.0      0.0     0.0     0.0     0.0      0.0     0.0   
376108      0.0     0.0      0.0     0.0     0.0     0.0      0.0     0.0   
470560      0.0     0.0      0.0     0.0     0.0     0.0      0.0     0.0   

             8        9       10      11               LeakType  
303190     0.0      0.0      0.0     0.0     Longitudinal Crack  
34830      0.0      0.0      0.0     0.0     Longitudinal Crack  
745073     NaN      NaN      NaN    95.0                NonLeak  
91507   -546.0  19009.0  13902.0  6780.0           Orifice Leak  
599857   665.0    603.0   1478.0     NaN            Gasket Leak  
...        ...      ...      ...     ...                    ...  
332203  2697.0   1840.0  -4219.0  -152.0     Longitudinal Crack  
643244     NaN      NaN      0.0     0.0     Longitudinal Crack  
81416      0.0      0.0      0.0     0.0           Orifice Leak  
376108     0.0      0.0      0.0     0.0  Circumferential Crack  
470560     0.0      0.0      0.0     0.0                NonLeak  

[3790100 rows x 13 columns]

In [9]:
data= data.sample(frac=1,random_state=55)
data

0       1       2        3       4       5       6       7  \
75942       0.0     0.0     0.0      0.0     0.0     0.0     0.0     0.0   
18161    7732.0 -2715.0   824.0  14682.0 -7184.0 -3794.0  5305.0   187.0   
792935      NaN     NaN     NaN      NaN     NaN     NaN     NaN  3692.0   
507231 -13884.0  1944.0 -2723.0  -1584.0 -2464.0 -5431.0  7422.0 -2708.0   
757194      NaN     NaN     NaN      NaN     NaN     NaN     NaN     0.0   
...         ...     ...     ...      ...     ...     ...     ...     ...   
274673   4382.0 -1511.0 -9933.0   9077.0   130.0   -67.0   968.0 -8245.0   
860284      NaN     NaN     NaN      NaN     NaN     NaN     NaN     0.0   
430245   2875.0 -8329.0   106.0   8222.0   308.0 -9461.0  -608.0 -5968.0   
502320      0.0     0.0     0.0      0.0     0.0     0.0     0.0     0.0   
431018      0.0     0.0     0.0      0.0     0.0     0.0     0.0     0.0   

             8       9      10      11               LeakType  
75942      0.0     0.0     0.0     0.0     Longitudinal Crack  
18161   1405.0  2311.0 -2252.0 -1063.0     Longitudinal Crack  
792935     NaN     NaN     NaN  -390.0                NonLeak  
507231 -3549.0 -2429.0  2034.0  1969.0            Gasket Leak  
757194     NaN     NaN     NaN     0.0                NonLeak  
...        ...     ...     ...     ...                    ...  
274673 -1725.0 -2721.0  2455.0  1325.0                NonLeak  
860284     NaN     NaN     NaN     0.0                NonLeak  
430245 -1521.0  1483.0   984.0  4049.0  Circumferential Crack  
502320     0.0     0.0     0.0     0.0           Orifice Leak  
431018     0.0     0.0     0.0     0.0           Orifice Leak  

[3790100 rows x 13 columns]

In [10]:
data['LeakType'].unique()

array(['Longitudinal Crack', 'NonLeak', 'Gasket Leak',
       'Circumferential Crack', 'Orifice Leak'], dtype=object)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3790100 entries, 75942 to 431018
Data columns (total 13 columns):
 #   Column    Dtype  
---  ------    -----  
 0   0         float64
 1   1         float64
 2   2         float64
 3   3         float64
 4   4         float64
 5   5         float64
 6   6         float64
 7   7         float64
 8   8         float64
 9   9         float64
 10  10        float64
 11  11        float64
 12  LeakType  object 
dtypes: float64(12), object(1)
memory usage: 404.8+ MB


In [12]:
data.describe()

0             1             2             3             4  \
count  3.140100e+06  3.172100e+06  2.985100e+06  3.153100e+06  3.112100e+06   
mean   6.592343e+00  1.911323e+00  1.580739e+01  7.747343e+00  6.294174e+00   
std    4.482886e+03  3.594062e+03  5.625345e+03  4.199570e+03  4.222823e+03   
min   -3.276800e+04 -3.276800e+04 -3.276800e+04 -3.276800e+04 -3.013200e+04   
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    1.700000e+01  1.400000e+01  3.900000e+01  2.100000e+01  3.000000e+00   
max    3.276700e+04  3.276700e+04  3.276700e+04  3.276700e+04  2.936400e+04   

                  5             6             7             8             9  \
count  3.167600e+06  3.202100e+06  3.743600e+06  3.215600e+06  3.020100e+06   
mean   5.477241e+00  8.107469e+00  2.092767e+00 -1.473049e+00  2.897549e+00   
std    4.477154e+03  4.197460e+03  3.838958e+03  2.708791e+03  3.646515e+03   
min   -3.276800e+04 -3.276800e+04 -3.276800e+04 -3.276800e+04 -3.276800e+04   
25%    0.000000e+00  0.000000e+00  0.000000e+00 -6.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    2.000000e+00  0.000000e+00  1.100000e+01  0.000000e+00  1.000000e+00   
max    3.276700e+04  3.276700e+04  3.276700e+04  3.276700e+04  3.276700e+04   

                 10            11  
count  3.030100e+06  3.413600e+06  
mean   4.440110e+00  2.496063e+00  
std    3.889505e+03  3.891013e+03  
min   -3.276800e+04 -3.276800e+04  
25%   -6.000000e+00  0.000000e+00  
50%    0.000000e+00  0.000000e+00  
75%    0.000000e+00  3.000000e+00  
max    3.276700e+04  3.276700e+04

In [13]:
data.nunique()

0           47526
1           43396
2           53760
3           44380
4           46741
5           51124
6           47134
7           47811
8           31447
9           46846
10          43398
11          50046
LeakType        5
dtype: int64

In [14]:
data.isna().sum()

0           650000
1           618000
2           805000
3           637000
4           678000
5           622500
6           588000
7            46500
8           574500
9           770000
10          760000
11          376500
LeakType         0
dtype: int64

In [15]:
data = data.dropna()
data.isna().sum()

0           0
1           0
2           0
3           0
4           0
5           0
6           0
7           0
8           0
9           0
10          0
11          0
LeakType    0
dtype: int64

In [16]:
print(data.shape)
data = data.drop_duplicates()
print(data.shape)

(2880100, 13)
(1440055, 13)


In [17]:
data.describe()

0             1             2             3             4  \
count  1.440055e+06  1.440055e+06  1.440055e+06  1.440055e+06  1.440055e+06   
mean   1.131624e+01  2.203460e+00  2.991112e+01  1.530527e+01  1.461959e+01   
std    6.239134e+03  5.100663e+03  7.946006e+03  6.130534e+03  6.082696e+03   
min   -3.276800e+04 -3.276800e+04 -3.276800e+04 -3.276800e+04 -3.013200e+04   
25%   -3.113000e+03 -2.177000e+03 -4.671500e+03 -3.541000e+03 -2.749000e+03   
50%    1.700000e+01  1.600000e+01  4.100000e+01  1.600000e+01  2.000000e+00   
75%    3.133000e+03  2.168000e+03  4.724000e+03  3.582000e+03  2.746000e+03   
max    3.276700e+04  3.276700e+04  3.276700e+04  3.276700e+04  2.936400e+04   

                  5             6             7             8             9  \
count  1.440055e+06  1.440055e+06  1.440055e+06  1.440055e+06  1.440055e+06   
mean   8.376593e+00  1.879975e+01  1.203628e+00 -4.033742e+00  6.668209e+00   
std    6.320390e+03  6.074615e+03  5.930784e+03  3.951048e+03  5.256490e+03   
min   -3.276800e+04 -3.276800e+04 -3.276800e+04 -3.276800e+04 -3.276800e+04   
25%   -2.613000e+03 -2.911000e+03 -2.900000e+03 -2.134000e+03 -1.956000e+03   
50%    3.000000e+00  0.000000e+00  9.000000e+00 -6.000000e+00  2.000000e+00   
75%    2.644000e+03  2.982000e+03  2.893000e+03  2.126000e+03  1.958000e+03   
max    3.276700e+04  3.276700e+04  3.276700e+04  3.276700e+04  3.276700e+04   

                 10            11  
count  1.440055e+06  1.440055e+06  
mean   9.975854e+00  7.157557e+00  
std    5.521399e+03  5.916333e+03  
min   -3.276800e+04 -3.276800e+04  
25%   -2.810000e+03 -2.671000e+03  
50%   -1.000000e+00  1.000000e+01  
75%    2.839000e+03  2.671000e+03  
max    3.276700e+04  3.276700e+04

In [18]:
label_encoder = LabelEncoder()
data['category_label_encoded'] = label_encoder.fit_transform(data['LeakType'])

In [19]:
X = data.drop(['LeakType', 'category_label_encoded'], axis=1)  # Features
y = pd.DataFrame(data['category_label_encoded'])  # Target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
model.save("hydrophone-branched_model.h5")
print("saved")

saved


In [20]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:
# Build DNN model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(5, activation='softmax'))  # Output layer, 5 for the number of unique categories

# Compile model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
# Train model
history = model.fit(X_train_scaled, y_train, epochs=5, batch_size=16, validation_data=(X_test_scaled, y_test))
model.summary()

Epoch 1/5
72003/72003 [==============================] - 150s 2ms/step - loss: 0.0510 - accuracy: 0.9823 - val_loss: 0.0259 - val_accuracy: 0.9906
Epoch 2/5
72003/72003 [==============================] - 146s 2ms/step - loss: 0.0227 - accuracy: 0.9917 - val_loss: 0.0166 - val_accuracy: 0.9939
Epoch 3/5
72003/72003 [==============================] - 143s 2ms/step - loss: 0.0169 - accuracy: 0.9939 - val_loss: 0.0195 - val_accuracy: 0.9929
Epoch 4/5
72003/72003 [==============================] - 145s 2ms/step - loss: 0.0139 - accuracy: 0.9952 - val_loss: 0.0161 - val_accuracy: 0.9948
Epoch 5/5
72003/72003 [==============================] - 146s 2ms/step - loss: 0.0120 - accuracy: 0.9960 - val_loss: 0.0130 - val_accuracy: 0.9966
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                832       
                                               

In [23]:
# Evaluate model
test_loss, test_accuracy = model.evaluate(X_test_scaled, y_test)
print(f'Test Loss: {test_loss:.4f}')
print(f'Test Accuracy: {test_accuracy:.4f}')

# Make predictions
y_pred = model.predict(X_test_scaled)

9001/9001 [==============================] - 13s 1ms/step - loss: 0.0130 - accuracy: 0.9966
Test Loss: 0.0130
Test Accuracy: 0.9966
9001/9001 [==============================] - 10s 1ms/step


In [24]:
y_pred_classes = np.argmax(y_pred, axis=1)  # Convert probabilities to class labels
conf_matrix = confusion_matrix(np.argmax(y_test, axis=1), y_pred_classes)
print(conf_matrix)

[[57519 58552 58367 55539 58034]
 [    0     0     0     0     0]
 [    0     0     0     0     0]
 [    0     0     0     0     0]
 [    0     0     0     0     0]]


In [27]:
sample_inputs = X_test_scaled[:10]

predictions = model.predict(sample_inputs)

# Get the index of the predicted classes
predicted_classes = predictions.argmax(axis=1)

# Map the index of classes to the original leak types using the class_labels list
predicted_leak_types = label_encoder.inverse_transform(predicted_classes)

# Print the index and the corresponding leak types for the first 10 data points
for index in range(10):
    # Get the index and the corresponding leak type
    leak_type_index = predicted_classes[index]
    leak_type = predicted_leak_types[index]

    print(f"Sample {index + 1}:")
    print("Index:", leak_type_index)
    # You can optionally print the input features if needed
    # print("Features:", sample_inputs[index])
    print("Leak Type:", leak_type)
    print("\n")

1/1 [==============================] - 0s 25ms/step
Sample 1:
Index: 4
Leak Type: Orifice Leak


Sample 2:
Index: 2
Leak Type: Longitudinal Crack


Sample 3:
Index: 2
Leak Type: Longitudinal Crack


Sample 4:
Index: 3
Leak Type: NonLeak


Sample 5:
Index: 1
Leak Type: Gasket Leak


Sample 6:
Index: 3
Leak Type: NonLeak


Sample 7:
Index: 2
Leak Type: Longitudinal Crack


Sample 8:
Index: 4
Leak Type: Orifice Leak


Sample 9:
Index: 2
Leak Type: Longitudinal Crack


Sample 10:
Index: 4
Leak Type: Orifice Leak


